import { z } from "zod";

export type LiveRow = Record<string, string> & { id?: string };

export type FieldConfig = {
  name: string;
  label: string;
  type?: "text" | "number" | "date" | "textarea" | "select";
  options?: string[];
  placeholder?: string;
};

export type ModuleConfig = {
  slug: string;
  title: string;
  eyebrow: string;
  description: string;
  table: string;
  columns: string[];
  titleKey: string;
  subtitleKey?: string;
  orderBy?: string;
  formTitle: string;
  createLabel: string;
  fields: FieldConfig[];
  schema: z.ZodObject<Record<string, z.ZodTypeAny>>;
  emptyTitle: string;
  emptyMessage: string;
  realtime?: boolean;
};

const required = (label: string) => z.string().trim().min(1, `${label} is required`).max(240, `${label} is too long`);
const optional = z.string().trim().max(500).optional().or(z.literal(""));
const nonNegative = z.coerce.number().min(0).transform(String);

export const moduleConfigs = {
  dataSources: {
    slug: "data-sources",
    title: "Data Sources",
    eyebrow: "Source trust",
    description: "Register first-party data origins, ownership, risk, consent defaults, and allowed use before activation.",
    table: "data_sources",
    columns: ["id", "name", "source_type", "owner", "risk", "consent_default", "allowed_use", "status", "created_at"],
    titleKey: "name",
    subtitleKey: "source_type",
    formTitle: "Add / edit data source",
    createLabel: "Save data source",
    fields: [
      { name: "name", label: "Name" },
      { name: "source_type", label: "Source type" },
      { name: "owner", label: "Owner" },
      { name: "risk", label: "Risk", type: "select", options: ["low", "medium", "high", "blocked"] },
      { name: "consent_default", label: "Consent default", type: "select", options: ["granted", "transactional", "aggregate", "unknown", "needs_review", "revoked"] },
      { name: "allowed_use", label: "Allowed use", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: ["active", "needs_review", "quarantined", "blocked"] },
    ],
    schema: z.object({ name: required("Name"), source_type: required("Source type"), owner: optional, risk: required("Risk"), consent_default: required("Consent default"), allowed_use: required("Allowed use"), status: required("Status") }),
    emptyTitle: "No data sources registered",
    emptyMessage: "Add a trusted source before imports or audiences can use real data.",
    realtime: true,
  },
  imports: {
    slug: "imports",
    title: "Imports",
    eyebrow: "Guided workflow",
    description: "Import work is staged, mapped, reviewed, and quarantined before records influence activation.",
    table: "import_jobs",
    columns: ["id", "batch_name", "source_name", "status", "total_rows", "accepted_rows", "quarantined_rows", "created_at"],
    titleKey: "batch_name",
    subtitleKey: "status",
    formTitle: "Start import job",
    createLabel: "Create import job",
    fields: [
      { name: "batch_name", label: "Batch name" },
      { name: "source_name", label: "Source name" },
      { name: "status", label: "Status", type: "select", options: ["draft", "mapping_required", "needs_review", "processing", "completed", "failed"] },
      { name: "total_rows", label: "Total rows", type: "number" },
      { name: "accepted_rows", label: "Accepted rows", type: "number" },
      { name: "quarantined_rows", label: "Quarantined rows", type: "number" },
    ],
    schema: z.object({ batch_name: required("Batch name"), source_name: required("Source name"), status: required("Status"), total_rows: nonNegative, accepted_rows: nonNegative, quarantined_rows: nonNegative }),
    emptyTitle: "No import jobs",
    emptyMessage: "Create an import shell, map fields, and review quarantine counts before activation.",
    realtime: true,
  },
  profiles: {
    slug: "profiles",
    title: "Profiles",
    eyebrow: "Masked identity",
    description: "Inspect operational profile state without exposing raw PII in UI, logs, client state, or console output.",
    table: "profiles",
    columns: ["id", "profile_key", "lifecycle", "consent", "suppression", "risk", "identity_keys", "created_at"],
    titleKey: "profile_key",
    subtitleKey: "lifecycle",
    formTitle: "Create / update profile",
    createLabel: "Save profile",
    fields: [
      { name: "profile_key", label: "Masked profile key" },
      { name: "lifecycle", label: "Lifecycle" },
      { name: "consent", label: "Consent", type: "select", options: ["granted", "unknown", "revoked", "denied", "needs_review"] },
      { name: "suppression", label: "Suppression", type: "select", options: ["not_suppressed", "suppressed", "chargeback", "opt_out"] },
      { name: "risk", label: "Risk", type: "select", options: ["low", "medium", "high", "blocked"] },
      { name: "identity_keys", label: "Masked identity keys" },
    ],
    schema: z.object({ profile_key: required("Profile key"), lifecycle: required("Lifecycle"), consent: required("Consent"), suppression: required("Suppression"), risk: required("Risk"), identity_keys: optional }),
    emptyTitle: "No operational profiles",
    emptyMessage: "Create masked profile records from reviewed imports or events.",
    realtime: true,
  },
  consent: {
    slug: "consent-suppression",
    title: "Consent & Suppression",
    eyebrow: "Dominant safety layer",
    description: "Record consent rules and suppression controls that block activation when status is unknown, revoked, or suppressed.",
    table: "consent_rules",
    columns: ["id", "rule_type", "status", "action", "risk", "source", "created_at"],
    titleKey: "rule_type",
    subtitleKey: "status",
    formTitle: "Add consent / suppression rule",
    createLabel: "Save rule",
    fields: [
      { name: "rule_type", label: "Rule type" },
      { name: "status", label: "Status", type: "select", options: ["granted", "unknown", "revoked", "active", "suppressed"] },
      { name: "action", label: "Action", type: "textarea" },
      { name: "risk", label: "Risk", type: "select", options: ["low", "medium", "high", "blocked"] },
      { name: "source", label: "Source" },
    ],
    schema: z.object({ rule_type: required("Rule type"), status: required("Status"), action: required("Action"), risk: required("Risk"), source: optional }),
    emptyTitle: "No consent rules",
    emptyMessage: "Add consent and suppression rules before building activation audiences.",
    realtime: true,
  },
  audiences: {
    slug: "audiences",
    title: "Audiences",
    eyebrow: "Consent-safe builder",
    description: "Build segments that respect source trust, consent, identifier quality, and suppression before destination fit.",
    table: "audiences",
    columns: ["id", "name", "preset", "total_count", "eligible_count", "suppressed_count", "status", "created_at"],
    titleKey: "name",
    subtitleKey: "status",
    formTitle: "Save audience draft",
    createLabel: "Save audience",
    fields: [
      { name: "name", label: "Audience name" },
      { name: "preset", label: "Preset" },
      { name: "total_count", label: "Total count", type: "number" },
      { name: "eligible_count", label: "Eligible count", type: "number" },
      { name: "suppressed_count", label: "Suppressed count", type: "number" },
      { name: "status", label: "Status", type: "select", options: ["draft", "review", "ready", "blocked"] },
    ],
    schema: z.object({ name: required("Audience name"), preset: optional, total_count: nonNegative, eligible_count: nonNegative, suppressed_count: nonNegative, status: required("Status") }),
    emptyTitle: "No audiences",
    emptyMessage: "Save a draft audience to preview consent-safe eligibility.",
    realtime: true,
  },
  destinations: {
    slug: "destinations",
    title: "Destinations",
    eyebrow: "Connector control",
    description: "Manage activation destinations with explicit connector modes, approval gates, and sync status.",
    table: "destinations",
    columns: ["id", "platform", "mode", "status", "last_sync_status", "created_at"],
    titleKey: "platform",
    subtitleKey: "mode",
    formTitle: "Add / edit destination",
    createLabel: "Save destination",
    fields: [
      { name: "platform", label: "Platform" },
      { name: "mode", label: "Mode", type: "select", options: ["sandbox", "read_only", "approval_required", "guarded_autopilot", "disabled"] },
      { name: "status", label: "Status", type: "select", options: ["not_connected", "connected", "needs_review", "blocked"] },
      { name: "last_sync_status", label: "Last sync status" },
    ],
    schema: z.object({ platform: required("Platform"), mode: required("Mode"), status: required("Status"), last_sync_status: optional }),
    emptyTitle: "No destinations",
    emptyMessage: "Add a destination in read-only or approval-required mode before any sync workflow.",
    realtime: true,
  },
  products: {
    slug: "products",
    title: "Products",
    eyebrow: "Economics",
    description: "Track price, cost, gross margin, inventory, refund rate, and risk before campaigns are prepared.",
    table: "products",
    columns: ["id", "name", "price", "cost", "margin_status", "inventory_status", "risk", "created_at"],
    titleKey: "name",
    subtitleKey: "margin_status",
    formTitle: "Add / edit product",
    createLabel: "Save product",
    fields: [
      { name: "name", label: "Product name" },
      { name: "price", label: "Price", type: "number" },
      { name: "cost", label: "Cost", type: "number" },
      { name: "margin_status", label: "Margin status" },
      { name: "inventory_status", label: "Inventory status" },
      { name: "risk", label: "Risk", type: "select", options: ["low", "medium", "high", "review", "blocked"] },
    ],
    schema: z.object({ name: required("Product name"), price: nonNegative, cost: nonNegative, margin_status: required("Margin status"), inventory_status: required("Inventory status"), risk: required("Risk") }),
    emptyTitle: "No products",
    emptyMessage: "Add products with real economics before attaching offers or campaigns.",
    realtime: true,
  },
  offers: {
    slug: "offers",
    title: "Offers",
    eyebrow: "Commercial matching",
    description: "Match offers to eligible audiences with payout, margin, conversion, refund risk, restrictions, and fit visible up front.",
    table: "offers",
    columns: ["id", "name", "offer_type", "margin", "refund_risk", "audience_fit", "status", "created_at"],
    titleKey: "name",
    subtitleKey: "offer_type",
    formTitle: "Add / edit offer",
    createLabel: "Save offer",
    fields: [
      { name: "name", label: "Offer name" },
      { name: "offer_type", label: "Offer type" },
      { name: "margin", label: "Margin / payout" },
      { name: "refund_risk", label: "Refund risk", type: "select", options: ["low", "medium", "high", "review"] },
      { name: "audience_fit", label: "Audience fit" },
      { name: "status", label: "Status", type: "select", options: ["draft", "review", "guarded", "approved", "blocked"] },
    ],
    schema: z.object({ name: required("Offer name"), offer_type: required("Offer type"), margin: optional, refund_risk: required("Refund risk"), audience_fit: optional, status: required("Status") }),
    emptyTitle: "No offers",
    emptyMessage: "Add offers with real restrictions and economics before campaigns use them.",
    realtime: true,
  },
  creatives: {
    slug: "creative-studio",
    title: "Creative Studio",
    eyebrow: "Draft to approval",
    description: "Create draft assets, route them through explicit approval, and only deploy after approved state is recorded.",
    table: "creatives",
    columns: ["id", "asset_name", "platform", "stage", "approval_state", "risk", "created_at"],
    titleKey: "asset_name",
    subtitleKey: "platform",
    formTitle: "Save creative draft",
    createLabel: "Save draft",
    fields: [
      { name: "asset_name", label: "Asset name" },
      { name: "platform", label: "Platform" },
      { name: "stage", label: "Stage" },
      { name: "approval_state", label: "Approval state", type: "select", options: ["draft", "approved", "deployed"] },
      { name: "risk", label: "Risk", type: "select", options: ["low", "medium", "high", "blocked"] },
    ],
    schema: z.object({ asset_name: required("Asset name"), platform: required("Platform"), stage: required("Stage"), approval_state: z.enum(["draft", "approved", "deployed"]), risk: required("Risk") }),
    emptyTitle: "No creative drafts",
    emptyMessage: "Save drafts first. Approval and deployment are explicit state transitions.",
    realtime: true,
  },
  campaigns: {
    slug: "campaigns",
    title: "Campaigns",
    eyebrow: "Launch control",
    description: "Campaigns are prepared and approval-gated before any spend, sync, publish, launch, or budget change.",
    table: "campaigns",
    columns: ["id", "name", "platform", "audience", "offer", "budget", "status", "approval_state", "readiness_score", "created_at"],
    titleKey: "name",
    subtitleKey: "platform",
    formTitle: "Create / update campaign draft",
    createLabel: "Save campaign",
    fields: [
      { name: "name", label: "Campaign name" },
      { name: "platform", label: "Platform" },
      { name: "audience", label: "Audience" },
      { name: "offer", label: "Offer" },
      { name: "budget", label: "Budget", type: "number" },
      { name: "status", label: "Status", type: "select", options: ["draft", "prepare", "ready", "blocked", "paused"] },
      { name: "approval_state", label: "Approval state", type: "select", options: ["required", "requested", "approved", "rejected"] },
      { name: "readiness_score", label: "Readiness score", type: "number" },
    ],
    schema: z.object({ name: required("Campaign name"), platform: required("Platform"), audience: optional, offer: optional, budget: nonNegative, status: required("Status"), approval_state: required("Approval state"), readiness_score: nonNegative }),
    emptyTitle: "No campaign drafts",
    emptyMessage: "Create a draft campaign and request approval before any launch path is available.",
    realtime: true,
  },
  events: {
    slug: "events",
    title: "Events",
    eyebrow: "Attribution health",
    description: "Ingest event facts used for retargeting, suppression, and payment-truth reporting.",
    table: "events",
    columns: ["id", "event_type", "source", "quality", "profile_key", "occurred_at", "created_at"],
    titleKey: "event_type",
    subtitleKey: "source",
    formTitle: "Ingest event",
    createLabel: "Save event",
    fields: [
      { name: "event_type", label: "Event type", type: "select", options: ["PageView", "ViewContent", "Lead", "InitiateCheckout", "Purchase", "Refund", "Chargeback", "OptOut"] },
      { name: "source", label: "Source" },
      { name: "quality", label: "Quality", type: "select", options: ["low", "medium", "high", "highest", "system_critical", "needs_review"] },
      { name: "profile_key", label: "Masked profile key" },
    ],
    schema: z.object({ event_type: required("Event type"), source: required("Source"), quality: required("Quality"), profile_key: optional }),
    emptyTitle: "No events",
    emptyMessage: "Ingest PageView, Purchase, Refund, Chargeback, and OptOut facts from real sources.",
    realtime: true,
  },
  reports: {
    slug: "reports",
    title: "Reports",
    eyebrow: "Profit-first reporting",
    description: "Revenue, profit, refund, and audience quality reporting from live analytic views.",
    table: "analytics_views",
    columns: ["id", "metric_name", "metric_value", "period", "status", "created_at"],
    titleKey: "metric_name",
    subtitleKey: "period",
    formTitle: "Record analytics metric",
    createLabel: "Save metric",
    fields: [
      { name: "metric_name", label: "Metric name" },
      { name: "metric_value", label: "Metric value" },
      { name: "period", label: "Period" },
      { name: "status", label: "Status", type: "select", options: ["ledger", "calculated", "guarded", "review"] },
    ],
    schema: z.object({ metric_name: required("Metric name"), metric_value: required("Metric value"), period: required("Period"), status: required("Status") }),
    emptyTitle: "No analytics metrics",
    emptyMessage: "Metrics appear after live events, payments, and approved campaign records are written.",
    realtime: true,
  },
  auditLogs: {
    slug: "audit-logs",
    title: "Audit Logs",
    eyebrow: "Governance trail",
    description: "Sensitive actions are recorded for imports, consent changes, suppression changes, audiences, sync jobs, and recommendations.",
    table: "audit_logs",
    columns: ["id", "action", "entity_type", "entity_id", "actor_id", "created_at"],
    titleKey: "action",
    subtitleKey: "entity_type",
    formTitle: "Record audit event",
    createLabel: "Save audit event",
    fields: [
      { name: "action", label: "Action" },
      { name: "entity_type", label: "Entity type" },
      { name: "entity_id", label: "Entity id" },
    ],
    schema: z.object({ action: required("Action"), entity_type: required("Entity type"), entity_id: optional }),
    emptyTitle: "No audit logs",
    emptyMessage: "Audit records will appear as operators mutate live records.",
    realtime: true,
  },
  aiCopilot: {
    slug: "ai-copilot",
    title: "AI Copilot",
    eyebrow: "Controlled recommendations",
    description: "AI recommendations are draft-only records that cannot spend, sync, publish, launch, or change suppression.",
    table: "ai_recommendations",
    columns: ["id", "recommendation", "expected_impact", "reason", "risk", "confidence", "approval_state", "created_at"],
    titleKey: "recommendation",
    subtitleKey: "reason",
    formTitle: "Create recommendation draft",
    createLabel: "Save recommendation",
    fields: [
      { name: "recommendation", label: "Recommendation" },
      { name: "expected_impact", label: "Expected impact" },
      { name: "reason", label: "Reason", type: "textarea" },
      { name: "risk", label: "Risk", type: "select", options: ["low", "medium", "high", "blocked"] },
      { name: "confidence", label: "Confidence" },
      { name: "approval_state", label: "Approval state", type: "select", options: ["draft", "requested", "approved", "rejected", "blocked"] },
    ],
    schema: z.object({ recommendation: required("Recommendation"), expected_impact: optional, reason: required("Reason"), risk: required("Risk"), confidence: optional, approval_state: required("Approval state") }),
    emptyTitle: "No recommendations",
    emptyMessage: "Draft AI recommendations can be recorded for human review.",
    realtime: true,
  },
  marketplaces: {
    slug: "marketplaces",
    title: "Marketplaces",
    eyebrow: "Commerce channels",
    description: "Track official channels, listings, orders, inventory, profit, and approved connector readiness.",
    table: "marketplaces",
    columns: ["id", "channel", "listing_status", "order_status", "inventory_status", "profit_status", "created_at"],
    titleKey: "channel",
    subtitleKey: "listing_status",
    formTitle: "Add marketplace channel",
    createLabel: "Save channel",
    fields: [
      { name: "channel", label: "Channel" },
      { name: "listing_status", label: "Listing status" },
      { name: "order_status", label: "Order status" },
      { name: "inventory_status", label: "Inventory status" },
      { name: "profit_status", label: "Profit status" },
    ],
    schema: z.object({ channel: required("Channel"), listing_status: required("Listing status"), order_status: optional, inventory_status: optional, profit_status: optional }),
    emptyTitle: "No marketplaces",
    emptyMessage: "Add channels once approved connector workflows are ready.",
    realtime: true,
  },
  settings: {
    slug: "settings",
    title: "Settings",
    eyebrow: "Governance",
    description: "Workspace controls for permissions, connector modes, approval rules, audit policy, diagnostics, and consent/suppression defaults.",
    table: "workspace_settings",
    columns: ["id", "setting_key", "setting_value", "category", "status", "created_at"],
    titleKey: "setting_key",
    subtitleKey: "category",
    formTitle: "Add / edit governance setting",
    createLabel: "Save setting",
    fields: [
      { name: "setting_key", label: "Setting key" },
      { name: "setting_value", label: "Setting value", type: "textarea" },
      { name: "category", label: "Category" },
      { name: "status", label: "Status", type: "select", options: ["active", "review", "blocked"] },
    ],
    schema: z.object({ setting_key: required("Setting key"), setting_value: required("Setting value"), category: required("Category"), status: required("Status") }),
    emptyTitle: "No workspace settings",
    emptyMessage: "Add governance defaults that control approval, audit, consent, and connector behavior.",
    realtime: true,
  },
} as const satisfies Record<string, ModuleConfig>;

export type ModuleKey = keyof typeof moduleConfigs;
